#! /bin/bash
# 
# 
# /etc/init.d/geoserver_logger
#
### BEGIN INIT INFO
# Provides: geoserver_logger
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Logs Geoserver access
# Description:    Controls python script that daemonizes and inserts in DB the access to geoserver. More configuration option in logDaemon.py
### END INIT INFO

# Activate the python virtual environment
#    . /path_to_virtualenv/activate

case "$1" in
  start)
    echo "Starting Geoserver Log"
    # Start the daemon
    python /usr/local/bin/logDaemon.py start
    ;;
  stop)
    echo "Stopping Geoserver Log"
    # Stop the daemon
    python /usr/local/bin/logDaemon.py stop
    ;;
  restart)
    echo "Restarting Geoserver log"
    python /usr/local/bin/logDaemon.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/geoserver_log {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
